name: Checkmarx AST Scan
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Checkmarx AST Github Action
        uses: Checkmarx/ast-github-action@master
        with:
          base_uri: https://eu.ast.checkmarx.net
          cx_tenant: French_team
          cx_client_id: ${{ secrets.CXAST_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CXAST_SECRET }}
