name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master #Github Action version
        with:
          project_name: Decathlon-WebGoat-V2-from-Github-Action
          cx_tenant: david_tenant
          base_uri: https://eu.ast.checkmarx.net # https://ast-master.dev.cxast.net #
          cx_client_id: ${{ secrets.CXAST_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CxAST_SECRET }}
          scan_types: sast,kics,sca
